[package]
name = "events"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
fs_extra = "1.3.0"
liquid = "0.26"
liquid-core = "0.26"

serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
strum = "0.26.3"
strum_macros = "0.26.4"
